### ISSUE TITLE
Android work space can not be built after polaris.5.OldShamefulAnt.zip is installed by magisk

### ISSUE THREAD

**Issue by Chocofate** [XEonAX/ANXCamera10#15]
**Device：**

Name：Xiaomi Mix2S Polaris
Color：White
CPU：Qualcomm® Snapdragon™ 845
RAM：8GB of LP-DDR4X
ROM：256GB
CPU Arch：ARM64

**Problem：**

Com.android.managedprovisioning will crash after polaris.5.OldShamefulAnt.zip is installed by magisk .

**Steps to replicate：**

1. Installing polaris.5.OldShamefulAnt.zip by magisk；
2. Installing Tset DPC from Play Store；
3. Opening Tset DPC to create work space .

**Logs：**

[android_work_crash.log](https://github.com/XEonAX/ANXCamera10/files/3283669/android_work_crash.log)

**Comment by XEonAX** [comment]
I believe this issue has been fixed in newer releases, It was a permissions issue
ff31267feffc7dd27bbd33b065818258e7ff0ec1
