### ISSUE TITLE
Pressing install on the 'Scan QR codes' option doesnt do anything.

### ISSUE THREAD

**Issue by Pistrie** [XEonAX/ANXCamera10#25]
Im running ANXCamera v179 and 48MPFix v170 on my Mi 9 (cepheus) phone with the latest Pixel Experience Plus rom. Going to 'settings -> Scan QR codes -> install' doesnt do anything. Is this a problem on my end?

Thanks!

**Comment by XEonAX** [comment]
There is no ANXScanner available for Q

**Comment by padiyes** [comment]
I'm using ANXScanner from [here](https://github.com/XEonAX/ANXMiuiApps/releases/download/23.master/ANXScanner_23.UnnaturalJadedRobin.apk), and the scanner can works properly (I'm on Android 11 under ArrowOS).
Is there any possibility to include this scanner to the ANXCam as well?
