### ISSUE TITLE
Update wiki for Redmi K20/Mi9T

### ISSUE THREAD

**Issue by alifarazz** [XEonAX/ANXCamera10#45]
Please contact @nckmml and tell him/her to update the [wiki entry for `davinci`](https://github.com/nckmml/ANXCamera/wiki/Redmi-K20-&-Mi-9T-(davinci)). 
Also, please update [this repo's wiki entry](https://github.com/XEonAX/ANXCamera10/wiki/Redmi-K20-&-Mi-9T-(davinci)) as well (if applicable).

#### Here's my experience which I think can be helpful in updating the wiki's entry
* ANXCamera works OK with LineageOS 17.1 with the latest version of Imagism (as writing this issue). The 48MP mode and the front-facing camera motor work as well. So far no boot-loops or any crashes.
* ##### How I installed ANXCamera
   - Using Magisk, I installed ``ANXFrameworkUnity_190.BountifulDistantHapuka.zip``, `ANXCameraUnity_190.BountifulDistantHapuka.zip` for ANXCamera and for addons, `Boot-loop Hot-fix for ANXCamera 190` (by noid) and `ANXCameraProvider v190` (also by noid); all of them without rebooting.
   - After rebooting, I manually enabled ANXCamera permissions and voilà! Everything works as expected 👍

---

[nckmml/ANXCamera](https://github.com/nckmml/ANXCamera) doesn't have *Issues* enabled so I had to make one in this repo.

**Comment by alifarazz** [comment]
By the way, I made this issue because there is no way to contribute to wikis on github.

**Comment by nckmml** [comment]
Thank you from your Contribution. Since there are 2 versions of LineageOS for davinci, please state which one (Official by Pig or Unofficial by Arian). Is Portrait mode working fine? Did you flash 48MPFix?

**Comment by alifarazz** [comment]
> Which LineageOS?

I'm using the official one by Pig.

> Is Portrait mode working fine?

Yep, everything works as expected.


> Did you flash 48MPFix?

Yes, I forgot to mention that. Specifically, I installed `48MPFixQ_181.GlossyIntelligentCock.zip` (by noid) using Magisk.

---

However, the second time I opened the app, It was showing black screen instead of camera's output. Also, I was confronted with a dialog box about `terms of service`, having 2 buttons: exit and allow. The dialog box was already popped up when I opened the app, so there was no delay. Now, It doesn't matter which I choose,  the app won't release the camera. I tried force-stopping it, cleaning it's data, but none of them helped. Finally, Android itself steps in and forces the camera module to turn off; causing the small camera icon in status bar, indicating the camera being used, to go away. However, this will cause the camera to malfunction.
After that, whenever I open ANXCamera, it will only show me the last frame it was able to capture. All other camera apps, such as Google Camera and Open Camera, will show a black screen (Open Camera, specifically, will show a message about not being able to connect to the camera, after a while). The only way to fix the malfunctioning camera is to reboot the device and never open ANXCamera again. To fix ANXCamera weird behavior, I have to disable all the relevant installed modules from Magisk, reboot, enable them, and reboot again.

**Comment by sorryusernameisalreadytaken** [comment]
Sadly I am not able to use ANXCamera on my davinci device.
I flashed in the same way and the same zips like alifarazz but I was not able to use the ANXCamera.

Any hints?

My los rom is: https://download.lineage.microg.org/davinci/

**Comment by nckmml** [comment]
From what I know Pig never provided support for ANXCamera in his LOS. It never worked properly there and as long as he doesn't want to work on it, there is nothing I could do. Arians unofficial LOS (17.1) is known to be compatible, tho. You can find download links for it on Telegram: https://t.me/lineage_davinci
