### ISSUE TITLE
[AppCrash] crDroid stuck at boot installing ANX framework

### ISSUE THREAD

**Issue by MCEventHorizon** [XEonAX/ANXCamera10#49]
**Describe the bug**
After installing ANX Framework 190 using Magisk or through TWRP, the phone is stuck at the boot screen. 
Just installing the CameraUnity(tried 190 and 185), I get this error: https://paste.crdroid.net/7UqtbL
**To Reproduce**
1. Install crDroid customROM
2. Install ANXFramework 190 through Magisk/Recovery
3. Stuck in boot
4. Removing it with TWRP file manager fixes the issue

**Expected behavior**

**Screenshots**

**ANXCamera (please complete the following information):**
 - 190
 - Pre-Built into Rom or Installed Manually [e.g Installed via Magisk]
 - Addons [e.g ANXFramework 190, 48MPFix 180]
   - ANXFramework 190
   
**Phone (please complete the following information):**
 - Device: Xiaomi Redmi Note 8 Pro
 - CodeName: begonia
 - ROM: crDroid
 - Vendor Version 7.11
 - Custom Vendor Don't Know
 - Official Miui Pie ROM available for your device? Yes

**Additional context**

**Attach LogCat after doing the following**
1. Restart Phone
2. Wait for it to idle
3. Clear Logs (adb logcat -c)
4. Start Camera, do the bug reproduction steps
5. Take Logcat (use alogcat or matlog, or adb logcat)
6. Attach Logcat to this bug report.

**Telegram username**
[for e.g @XEonAX]

**Additional context**

**Comment by XEonAX** [comment]
Flash the add-on Bootloop Fix v190. You can find it here.

**Comment by XEonAX** [comment]
Flash the add-on Bootloop Fix v190. You can find it here.

**Comment by MCEventHorizon** [comment]
I managed to fixed it by not installing framework at all, just ANX camera but the R version.
